### PR TITLE
Fix for bee name changes in resource packs

### PR DESCRIPTION
**Pull request by Hexicube**
StatCollector includes language files from resource packs, and should be used over LanguageRegistry which only includes language files from mod jars.

### CODE REVIEW

**Comment by MysteriousAges** [comment]
I have a strong aversion to if/else statements missing their braces. If you fix that, I'll merge.

**Comment by Hexicube** [comment]
Hahaha, sure thing.

**Comment by MysteriousAges** [comment]
As a side note, after pulling these changes, the code didn't compile because you'd missed the import for StatCollector.

Please make sure the code compiles with no errors and no more warnings than the original code in the future. ;)

**Comment by Hexicube** [comment]
Silly me, at least the error was obvious. I actually did the edit with the github edit because it was incredibly simple.

**Pull request merged**
